# Numpy

### Numpy Arrays and Array Methods

In [2]:
import numpy as np

In [3]:
mylist = np.array([1,2,3])

In [4]:
mylist

array([1, 2, 3])

In [5]:
type(mylist)

numpy.ndarray

In [6]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [8]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
10 * np.random.rand(5,5) * np.eye(5)

array([[7.13287452, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.87252341, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 9.73212539, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.40508045, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 3.82318454]])

In [14]:
np.random.randn(4, 5)

array([[-0.68048357, -0.09751905, -2.2033864 ,  0.54098259, -0.75689623],
       [ 1.21546894,  0.48522768, -0.63428932,  1.49473081,  0.2853828 ],
       [ 0.34754235, -0.46920319, -0.89769524,  1.21755589,  2.18185994],
       [-1.12877311, -0.78814306,  0.17816527, -0.84439357, -0.66957647]])

In [15]:
np.random.randint(1, 101, (4,5))

array([[ 6, 44, 65, 39, 31],
       [80, 36, 30, 94, 35],
       [20, 49, 42, 25, 81],
       [18,  9, 32, 92, 35]])

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# Will error is number of values does not equal rows * cols
try:
    arr.reshape(5,6)
except Exception as e: 
    print(e)


cannot reshape array of size 25 into shape (5,6)


In [20]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [21]:
ranarr.max()

99

In [22]:
ranarr.min()

2

In [23]:
ranarr.argmax()

5

In [24]:
ranarr.argmin()

7

In [25]:
ranarr.dtype

dtype('int32')

In [26]:
arrMatrix = arr.reshape(5,5)

In [27]:
arrMatrixColumns = arrMatrix.shape[1]
arrMatrixColumns

5

In [28]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

### Indexing

In [29]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[8]

8

In [31]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[:4]

array([0, 1, 2, 3])

In [34]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Broadcasting

In [35]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
arr = np.arange(0, 11)
# Creates reference (not copy)
slice_of_arr = arr[3:7]
print(arr)
print(slice_of_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [37]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99])

In [38]:
# arr changed due to slice_of_arr being a reference to arr not a copy of
arr

array([ 0,  1,  2, 99, 99, 99, 99,  7,  8,  9, 10])

In [39]:
# use .copy method to make copy of array
new_arr = arr.copy()
new_arr

array([ 0,  1,  2, 99, 99, 99, 99,  7,  8,  9, 10])

In [40]:
new_arr[2:-3] = 50
print(new_arr)
print(arr)


[ 0  1 50 50 50 50 50 50  8  9 10]
[ 0  1  2 99 99 99 99  7  8  9 10]


In [41]:
arr

array([ 0,  1,  2, 99, 99, 99, 99,  7,  8,  9, 10])

### n-Dimensional Arrays

In [42]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d.shape

(3, 3)

In [44]:
arr_2d[0]

array([ 5, 10, 15])

In [45]:
# getting values by indexing
arr_2d[1][1]

25

In [46]:
# getting values by row, column
arr_2d[1,1]

25

In [47]:
# getting muliple values
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

#### Conditional Selections

In [48]:
arr = np.arange(1, 13)
matrix_2d = arr.reshape(4,3)
print(arr)
print('\n')
print(matrix_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
# isindex value greater than 4 (bool)
mask_arr = arr > 4
mask_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [50]:
mask_matrix = matrix_2d > 4
mask_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
# Use mask to filter array
arr[mask_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
# pass mask as index filter
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
# Returns ARRAY of values meeting condition (not matrix)
matrix_2d[matrix_2d > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
matrix_2d[mask_matrix]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

### Numpy Operations and Broadcasting

In [55]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [61]:
(arr ** 2 + arr) ** 0.5

array([0.        , 1.41421356, 2.44948974, 3.46410162, 4.47213595,
       5.47722558, 6.4807407 , 7.48331477, 8.48528137, 9.48683298])

In [59]:
# Error/illegly operations are handled by filling values with nan and giving warning
# Warning will continue and you may miss the error (introduction of nan and inf)
arr / arr

C:\Users\patri\AppData\Local\Temp/ipykernel_13416/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
1 / arr

C:\Users\patri\AppData\Local\Temp/ipykernel_13416/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [63]:
np.log(arr)

C:\Users\patri\AppData\Local\Temp/ipykernel_13416/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Basic Statistics (Descriptive)

In [64]:
arr.sum()

45

In [65]:
arr.mean()

4.5

In [66]:
arr.max()

9

In [67]:
arr.min()

0

In [68]:
arr.var()

8.25

In [69]:
arr.std()

2.8722813232690143

In [71]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
arr_2d.sum()

300

In [73]:
# sum across the rows (axis = 0)
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [74]:
# sum across the columns (axis = 1)
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])